#ifndef INC_2025_1_LAB_09_CSV_ESTRUCTURAS_DINAMICAS_TABLADEINFRACCIONES_H
#define INC_2025_1_LAB_09_CSV_ESTRUCTURAS_DINAMICAS_TABLADEINFRACCIONES_H

struct TablaDeInfracciones{
    char* codigo;
    double multa;
    char* descripcion;
};
#endif //INC_2025_1_LAB_09_CSV_ESTRUCTURAS_DINAMICAS_TABLADEINFRACCIONES_H