#ifndef INC_2024_1_LAB_09_CSV_ESTRUCTURAS_DINAMICAS_CLIENTE_H
#define INC_2024_1_LAB_09_CSV_ESTRUCTURAS_DINAMICAS_CLIENTE_H

struct Cliente{
    int dni;
    char* nombre;
};
#endif //INC_2024_1_LAB_09_CSV_ESTRUCTURAS_DINAMICAS_CLIENTE_H
